### ISSUE TITLE
Make installation of lammps faster

### ISSUE THREAD

**Issue by itziakos** [simphony/simphony-framework#20]
Installing lammps is too slow due to cloning a very large repo. We should find ways to speed it up

**Comment by nathanfranklin** [comment]
Have issue (simphony/simphony-lammps-md#60) but will priotize this work.

**Comment by itziakos** [comment]
There are a number of things that we can try to do with git also. That is why I added the issue here. Thanks for linking it with the issue in lammps

**Comment by itziakos** [comment]
implemented in #24
