### ISSUE TITLE
Update supported and tested platform information

### ISSUE THREAD

**Issue by nathanfranklin** [simphony/simphony-framework#56]
Currently, we say `The SymPhoNy framework is developed and tested on Ubuntu 12.04 LTS`

Maybe we need to be more specific on what the supported and tested platform is.  As there is at least one known issue when using the framework on 32-bit Ubuntu (see simphony/simphony-jyulb#26)

**Comment by itziakos** [comment]
I agree, it should be  `Ubuntu 12.04 LTS 64bit`
