### ISSUE TITLE
openfoam version222?

### ISSUE THREAD

**Issue by jeremy-rutman** [simphony/simphony-framework#72]
not sure if openfoam version222 is required for some reason but it leads to install fail
Makefile line 104 
       apt-get install -y --force-yes openfoam222
can be replaced by 
        apt-get install -y --force-yes openfoam30
for instance -  I don't know if it will cause problems later but at least install works.

**Comment by itziakos** [comment]
The makefiles are for ubuntu 12.04. The latest version supported for that version of ubuntu is openfoam230

**Comment by itziakos** [comment]
Please also note that the version of openfoam to be used is dictated by the openfoam simphony wrapper

**Comment by stefanoborini** [comment]
Confirm 222 did not work. I am currently installing 230 on Precise, and 231 on Trusty (Because 230 is not working on Trusty, and 231 is not available on Precise)
